[package]
name = "bearTracks"
version = "4.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13"
actix-broker = "0.4"
actix-codec = "0.5"
actix-cors = "0.6"
actix-files = "0.6"
actix-http = "3.4"
actix-identity = "0.6"
actix-multipart = "0.6"
actix-multipart-derive = "0.6"
actix-protobuf = "0.10"
actix-session = "0.8"
actix-test = "0.1"
actix-tls = "3.1.1"
actix-utils = "3"
actix-web = "4.4"
actix-web-actors = "4.1"
actix-web-lab = "0.20"
actix-ws = "0.2.5"
awc = "3.2"

env_logger = "0.10"
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
log = "0.4"
r2d2 = "0.8"
r2d2_sqlite = "0.22"
rusqlite = "0.29"
serde = { version = "1", features = ["derive"] }
