[package]
name = "bear_tracks"
version = "4.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13"
actix-http = "3.4"
actix-web = "4.4"
actix-files = "0.6.2"
actix-session = { version = "~0.7", features = ["cookie-session"] }
argon2 = "0.5.2"
env_logger = "0.10"
futures-util = { version = "0.3.17", default-features = false, features = ["std"] }
log = "0.4"
r2d2 = "0.8"
r2d2_sqlite = "0.22"
rusqlite = "0.29"
serde = { version = "1", features = ["derive"] }
chrono = "0.4.31"
rand = "0.8.5"